name = "Yappernautics"
author = "Ozzer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1032c3460d0db0c2bb5dfef65216430377cf0d3f3b6fca94a5590b3a7a4eb7a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.232"
