name = "Yappernautics"
author = "Ozzer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12b2ee64872b8b2d615c069d66e6e1b8622c3a56d00bf2dd2513e86a45c73cb6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
