name = "Yappernautics"
author = "Ozzer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84e20e0a5c3d3a0e306409d1e83336d2d1e0781811294daa6b9470467047a0ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
